// Auto-generated by generate_lookup_tables.py from Motor_Para.xlsx
// DO NOT EDIT manually.

#include "Motor_Config.h"

const float Current_ID_PI_Ki_Lookup_1D[10] = {
    0.32044245f, 0.32044245f, 0.32044245f, 0.32044245f, 0.2136283f, 0.2136283f,
    0.16022122f, 0.14241886f, 0.12817698f, 0.12817698f,
};

const float Current_ID_PI_Kp_Lookup_1D[10] = {
    3.1415926f, 3.1415926f, 3.1415926f, 3.1415926f, 2.0943951f, 2.0943951f,
    1.5707963f, 1.3962634f, 1.256637f, 1.256637f,
};

const float Current_IQ_PI_Ki_Lookup_1D[10] = {
    0.32044245f, 0.32044245f, 0.32044245f, 0.32044245f, 0.2136283f, 0.2136283f,
    0.16022122f, 0.14241886f, 0.12817698f, 0.12817698f,
};

const float Current_IQ_PI_Kp_Lookup_1D[10] = {
    3.7070793f, 3.7070793f, 3.7070793f, 3.7070793f, 2.4713862f, 2.4713862f,
    1.8535396f, 1.6475908f, 1.4828317f, 1.4828317f,
};

const float Current_Lookup_Speed_index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float IF_Start_Iq_A[10] = {
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f,
};

const float IF_Start_Ramp_Sec[10] = {
    0.0f, 0.2f, 0.4f, 0.6f, 0.8f, 1.0f,
    1.2f, 1.4f, 1.6f, 2.0f,
};

const float IF_Start_Speed_RPM[10] = {
    20.0f, 50.0f, 100.0f, 200.0f, 400.0f, 600.0f,
    700.0f, 750.0f, 800.0f, 800.0f,
};

const float NonFlux_Gama_Lookup_1D[10] = {
    100000.0f, 100000.0f, 1000000.0f, 1000000.0f, 1000000.0f, 2000000.0f,
    3000000.0f, 4000000.0f, 5000000.0f, 5000000.0f,
};

const float NonFlux_Lookup_Speed_index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float NonFlux_PLL_Ki_Lookup_1D[10] = {
    0.54831134f, 0.54831134f, 2.1932453f, 4.934802f, 8.7729814f, 13.707783f,
    19.739208f, 26.867256f, 35.091926f, 54.831134f,
};

const float NonFlux_PLL_Kp_Lookup_1D[10] = {
    148.07373f, 148.07373f, 296.14746f, 444.22119f, 592.29492f, 740.36866f,
    888.44239f, 1036.5161f, 1184.5898f, 1480.7373f,
};

const float SMO_Gain_Lookup_1D[10] = {
    4.0f, 4.0f, 4.0f, 4.0f, 4.0f, 4.0f,
    4.0f, 4.0f, 4.0f, 4.0f,
};

const float SMO_Lookup_Speed_index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float SMO_PLL_Ki_Lookup_1D[10] = {
    0.25502853f, 0.25502853f, 0.51005706f, 0.76508559f, 1.0201141f, 1.2751426f,
    1.5301712f, 1.7851997f, 2.0402282f, 2.5502853f,
};

const float SMO_PLL_Kp_Lookup_1D[10] = {
    68.871503f, 68.871503f, 68.871503f, 68.871503f, 68.871503f, 68.871503f,
    68.871503f, 68.871503f, 68.871503f, 68.871503f,
};

const float Speed_Loop_Speed_Index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float Speed_Loop_Speed_PI_Ki_1D[10] = {
    9.1609e-05f, 7.1609e-05f, 6.1609e-05f, 5.1609e-05f, 5.1609e-05f, 7.3815823e-06f,
    7.3815823e-06f, 7.3815823e-06f, 7.3815823e-06f, 7.3815823e-06f,
};

const float Speed_Loop_Speed_PI_Kp_1D[10] = {
    0.00091755f, 0.00081755f, 0.00061755f, 0.00061755f, 0.00061755f, 0.00051755f,
    0.00091755f, 0.00091755f, 0.00091755f, 0.00091755f,
};
