// Auto-generated by generate.py from Motor_Para/Motor_Parameters.csv
// DO NOT EDIT manually.

#ifdef MOTOR_LOOKUP_TABLES_FLOAT

// Motor base parameters (from MotorBase section, values generated by generate.py)
#define MOTOR_POLE_PAIRS           (4.0f)
#define MOTOR_MAX_CURRENT_A        (20.0f)
#define MOTOR_VOLTAGE_LIMIT_V      (50.0f)
#define MOTOR_FLUX_RPM_PER_V       (4.3f)
#define MOTOR_RS                   (1.05f)
#define MOTOR_LD                   (0.0005f)
#define MOTOR_LQ                   (0.00059f)
#define MOTOR_POWER_LIMIT          (100.0f)

const float Current_ID_PI_Ki_Lookup_1D[10] = {
    0.21991149f, 0.21991149f, 0.21991149f, 0.21991149f, 0.21991149f, 0.21991149f,
    0.16493361f, 0.14660766f, 0.13194689f, 0.13194689f,
};

const float Current_ID_PI_Kp_Lookup_1D[10] = {
    2.0943951f, 2.0943951f, 2.0943951f, 2.0943951f, 2.0943951f, 2.0943951f,
    1.5707963f, 1.3962634f, 1.2566371f, 1.2566371f,
};

const float Current_IQ_PI_Ki_Lookup_1D[10] = {
    0.21991149f, 0.21991149f, 0.21991149f, 0.21991149f, 0.21991149f, 0.21991149f,
    0.16493361f, 0.14660766f, 0.13194689f, 0.13194689f,
};

const float Current_IQ_PI_Kp_Lookup_1D[10] = {
    2.4713862f, 2.4713862f, 2.4713862f, 2.4713862f, 2.4713862f, 2.4713862f,
    1.8535397f, 1.6475908f, 1.4828317f, 1.4828317f,
};

const float Current_Lookup_Speed_index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float EfFlux_Gama_Lookup_1D[10] = {
    100.0f, 100.0f, 100.0f, 100.0f, 200.0f, 200.0f,
    200.0f, 200.0f, 200.0f, 200.0f,
};

const float IF_Start_Iq_A[10] = {
    0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f,
};

const float IF_Start_Ramp_Sec[10] = {
    0.0f, 0.2f, 0.4f, 0.6f, 0.8f, 1.0f,
    1.2f, 1.4f, 1.6f, 2.0f,
};

const float IF_Start_Speed_RPM[10] = {
    5.0f, 10.0f, 30.0f, 50.0f, 60.0f, 70.0f,
    80.0f, 85.0f, 90.0f, 200.0f,
};

const float NonFlux_Gama_Lookup_1D[10] = {
    100000.0f, 100000.0f, 1000000.0f, 1000000.0f, 1000000.0f, 2000000.0f,
    3000000.0f, 4000000.0f, 5000000.0f, 5000000.0f,
};

const float NonFlux_Lookup_Is_index[10] = {
    3.0f, 3.0f, 6.0f, 9.0f, 12.0f, 15.0f,
    18.0f, 21.0f, 24.0f, 30.0f,
};

const float NonFlux_Lookup_Speed_index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float NonFlux_PLL_Ki_Lookup_1D[10] = {
    2.1932454f, 2.1932454f, 2.1932454f, 0.19739209f, 0.35091927f, 0.54831136f,
    0.78956835f, 1.0746903f, 1.4036771f, 2.1932454f,
};

const float NonFlux_PLL_Kp_Lookup_1D[10] = {
    296.14747f, 296.14747f, 837.75804f, 628.31853f, 837.75804f, 1047.1976f,
    1256.6371f, 1466.0766f, 1675.5161f, 2094.3951f,
};

const float SMO_Gain_Lookup_1D[10] = {
    4.0f, 4.0f, 4.0f, 4.0f, 4.0f, 4.0f,
    4.0f, 4.0f, 4.0f, 4.0f,
};

const float SMO_Lookup_Speed_index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float SMO_PLL_Ki_Lookup_1D[10] = {
    0.25502854f, 0.25502854f, 0.51005707f, 0.76508561f, 1.0201141f, 1.2751427f,
    1.5301712f, 1.7851998f, 2.0402283f, 2.5502854f,
};

const float SMO_PLL_Kp_Lookup_1D[10] = {
    68.871504f, 68.871504f, 68.871504f, 68.871504f, 68.871504f, 68.871504f,
    68.871504f, 68.871504f, 68.871504f, 68.871504f,
};

const float Speed_Loop_Speed_Index[10] = {
    500.0f, 500.0f, 1000.0f, 1500.0f, 2000.0f, 2500.0f,
    3000.0f, 3500.0f, 4000.0f, 5000.0f,
};

const float Speed_Loop_Speed_PI_Ki_1D[10] = {
    4.7e-05f, 4.7e-05f, 4.7e-05f, 8.36e-05f, 8.36e-05f, 8.36e-05f,
    8.36e-05f, 8.36e-05f, 8.36e-05f, 8.36e-05f,
};

const float Speed_Loop_Speed_PI_Kp_1D[10] = {
    0.00074f, 0.00074f, 0.00074f, 0.00042f, 0.00042f, 0.00042f,
    0.00042f, 0.00042f, 0.00042f, 0.00042f,
};

const float EFFlux_Angle_Comp_table_2D[10][10] = {
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
};

#endif
