// Auto-generated by generate.py from Motor_Para/Motor_Parameters.csv
// DO NOT EDIT manually.

// Motor base parameters (from MotorBase section, values generated by generate.py)
#define MOTOR_PN                   (4.0f)
#define MOTOR_CURRENT_MAX_A        (45.0f)
#define MOTOR_BUS_VOLTAGE_MAX      (86.0f)
#define MOTOR_FLUX_VKRPM           (4.3f)
#define MOTOR_FLUX_VS              (0.010265494f)
#define MOTOR_RS                   (1.05f)
#define MOTOR_LD                   (0.0005f)
#define MOTOR_LQ                   (0.00059f)
#define MOTOR_POWER_MAX_W          (100.0f)
#define MOTOR_SPEED_MAX_RPM        (5000.0f)

#ifdef MOTOR_LOOKUP_TABLES_FLOAT

const float Current_ID_PI_Ki_Lookup_1D[10] = {
    0.11506996f, 0.11506996f, 0.11506996f, 0.11506996f, 0.11506996f, 0.11506996f,
    0.086302473f, 0.076713309f, 0.069041978f, 0.069041978f,
};

const float Current_ID_PI_Kp_Lookup_1D[10] = {
    1.0959044f, 1.0959044f, 1.0959044f, 1.0959044f, 1.0959044f, 1.0959044f,
    0.82192831f, 0.73060294f, 0.65754265f, 0.65754265f,
};

const float Current_IQ_PI_Ki_Lookup_1D[10] = {
    0.11506996f, 0.11506996f, 0.11506996f, 0.11506996f, 0.11506996f, 0.11506996f,
    0.086302473f, 0.076713309f, 0.069041978f, 0.069041978f,
};

const float Current_IQ_PI_Kp_Lookup_1D[10] = {
    1.2931672f, 1.2931672f, 1.2931672f, 1.2931672f, 1.2931672f, 1.2931672f,
    0.96987541f, 0.86211147f, 0.77590033f, 0.77590033f,
};

const float Current_Lookup_Speed_index[10] = {
    0.1f, 0.1f, 0.2f, 0.3f, 0.4f, 0.5f,
    0.6f, 0.7f, 0.8f, 1.0f,
};

const float EfFlux_Gama_Lookup_1D[10] = {
    0.047746483f, 0.047746483f, 0.047746483f, 0.047746483f, 0.095492966f, 0.095492966f,
    0.095492966f, 0.095492966f, 0.095492966f, 0.095492966f,
};

const float IF_Start_Iq_A[10] = {
    0.0f, 0.02f, 0.02f, 0.02f, 0.02f, 0.02f,
    0.02f, 0.02f, 0.02f, 0.02f,
};

const float IF_Start_Ramp_Sec[10] = {
    0.0f, 0.2f, 0.4f, 0.6f, 0.8f, 1.0f,
    1.2f, 1.4f, 1.6f, 2.0f,
};

const float IF_Start_Speed_RPM[10] = {
    0.0f, 0.01f, 0.02f, 0.03f, 0.04f, 0.06f,
    0.08f, 0.09f, 0.095f, 0.1f,
};

const float NonFlux_Gama_Lookup_1D[10] = {
    47.746483f, 47.746483f, 477.46483f, 477.46483f, 477.46483f, 954.92966f,
    1432.3945f, 1909.8593f, 2387.3241f, 2387.3241f,
};

const float NonFlux_Lookup_Is_index[10] = {
    3.0f, 3.0f, 6.0f, 9.0f, 12.0f, 15.0f,
    18.0f, 21.0f, 24.0f, 30.0f,
};

const float NonFlux_Lookup_Speed_index[10] = {
    0.1f, 0.1f, 0.2f, 0.3f, 0.4f, 0.5f,
    0.6f, 0.7f, 0.8f, 1.0f,
};

const float NonFlux_PLL_Ki_Lookup_1D[10] = {
    0.00037699112f, 0.00037699112f, 0.0010471976f, 9.424778e-05f, 0.00016755161f, 0.00026179939f,
    0.00037699112f, 0.0005131268f, 0.00067020643f, 0.0010471976f,
};

const float NonFlux_PLL_Kp_Lookup_1D[10] = {
    0.08484f, 0.08484f, 0.4f, 0.3f, 0.4f, 0.5f,
    0.6f, 0.7f, 0.8f, 1.0f,
};

const float SMO_Gain_Lookup_1D[10] = {
    4.0f, 4.0f, 4.0f, 4.0f, 4.0f, 4.0f,
    4.0f, 4.0f, 4.0f, 4.0f,
};

const float SMO_Lookup_Speed_index[10] = {
    0.1f, 0.1f, 0.2f, 0.3f, 0.4f, 0.5f,
    0.6f, 0.7f, 0.8f, 1.0f,
};

const float SMO_PLL_Ki_Lookup_1D[10] = {
    0.25502854f, 0.25502854f, 0.51005707f, 0.76508561f, 1.0201141f, 1.2751427f,
    1.5301712f, 1.7851998f, 2.0402283f, 2.5502854f,
};

const float SMO_PLL_Kp_Lookup_1D[10] = {
    68.871504f, 68.871504f, 68.871504f, 68.871504f, 68.871504f, 68.871504f,
    68.871504f, 68.871504f, 68.871504f, 68.871504f,
};

const float Speed_Loop_Speed_Index[10] = {
    0.1f, 0.1f, 0.2f, 0.3f, 0.4f, 0.5f,
    0.6f, 0.7f, 0.8f, 1.0f,
};

const float Speed_Loop_Speed_PI_Ki_1D[10] = {
    0.0021874793f, 0.0021874793f, 0.0021874793f, 0.0038909207f, 0.0038909207f, 0.0038909207f,
    0.0038909207f, 0.0038909207f, 0.0038909207f, 0.0038909207f,
};

const float Speed_Loop_Speed_PI_Kp_1D[10] = {
    0.034441164f, 0.034441164f, 0.034441164f, 0.019547688f, 0.019547688f, 0.019547688f,
    0.019547688f, 0.019547688f, 0.019547688f, 0.019547688f,
};

const float EFFlux_Angle_Comp_table_2D[10][10] = {
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
    {-0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f, -0.05f},
};

#endif // MOTOR_LOOKUP_TABLES_FLOAT
